P8105 Homework 2
================
Lauren Holley

``` r
library(tidyverse)
library(readxl)
```

## Problem 1

``` r
subways_df = 
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  janitor::clean_names() |>
   pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name",
    values_transform = as.character
  ) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE),
    vending = case_match(
      vending,
      "YES" ~ TRUE,
      "NO" ~ FALSE),
      route_number = as.numeric(route_number)
  ) |>
  select(line:entry, vending, ada, route_number, route_name)
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

My steps for cleaning:

1.  `clean_names` to make all column names snake case.

2.  `pivot_longer` since the route columns were unnecessarily separated.
    I added a prefix “route” so only the number of the route was
    retained. Those numbers were then places into `route_number`. Values
    of each of these columns were sent to `route_name`, and then
    transformed to characters due to their mixed numeric and character
    nature.

3.  I did the suggested `case_match` step from instructions to create a
    logical assignment in the `entry` variable. I then realized that
    `vending` was also a chr variable and switched it to logical
    instead.

4.  I made route numbers numeric using `as.numeric`.

5.  I selected for the requested variables.

The `subways_df` dataset contains variable names: line, station_name,
station_latitude, station_longitude, entrance_type, entry, vending, ada,
route_number, route_name. The dataset includes 10 columns and 20548
rows.

``` r
nrow(distinct(subways_df, line, station_name))
```

    ## [1] 465

There are 465 distinct stations.

``` r
subways_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

There are 84 stations that are ADA compliant.

``` r
subways_df |>
  filter(vending == FALSE) |>
  summarize(proportion = mean(entry))
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1      0.377

37.7% of station entrances / exits without vending allow entrance.

``` r
subways_df |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 60

60 distinct stations serve the A train.

``` r
subways_df |>
  filter(route_name == "A", ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 17

17 stations that serve the A train are also ADA compliant.

## Problem 2

Importing the Trash Wheel data!!

``` r
mr_trash_df =
  readxl::read_excel(
    "data/Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N709"
    ) |>
  janitor::clean_names() |>
  mutate(
    sports_balls = as.integer(round(sports_balls, digits = 0)),
    year = as.numeric(year),
    trash_wheel = "mr"
  )

prof_trash_df =
  readxl::read_excel(
    "data/Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M134"
    ) |>
  janitor::clean_names() |>
  mutate(
    trash_wheel = "professor"
  )

gwynns_trash_df =
  readxl::read_excel(
    "data/Trash Wheel Collection Data.xlsx",
    sheet = "Gwynns Falls Trash Wheel",
    range = "A2:L351"
    ) |>
  janitor::clean_names() |>
  mutate(
    trash_wheel = "gwynns"
  )
```

Binding rows:

``` r
trash_wheel_df =
  bind_rows(mr_trash_df, prof_trash_df, gwynns_trash_df) |>
  relocate(trash_wheel)
```

The `trash_wheel_df` dataset contains variable names: trash_wheel,
dumpster, month, year, date, weight_tons, volume_cubic_yards,
plastic_bottles, polystyrene, cigarette_butts, glass_bottles,
plastic_bags, wrappers, sports_balls, homes_powered. The dataset
includes 15 columns and 1188 rows. Some key variables include
`trash_wheel` with values mr, professor, and gwynns, which indicate
which trash wheel the data originated from, and `weight_tons`,
signifying the weight in tons of trash collected through a `<dbl>`
value.

- The total weight collected by Professor Trash Wheel was 282.26 tons.

- The total number of cigarette butts collected by the Gwynns Falls
  Trash Wheel was 18120 in June 2022.

## Problem 3

``` r
baseline_df = (
  read_csv("data/MCI_baseline.csv",
           skip = 1,
           na = ".") |>
    janitor::clean_names() |>
    rename(bl_age = current_age) |>
    mutate(
      sex = case_match(
        sex,
        0 ~ "female",
        1 ~ "male"),
      apoe4 = case_match(
        apoe4,
        0 ~ "non_carrier",
        1 ~ "carrier")
    ) |>
    filter(is.na(age_at_onset) | age_at_onset > bl_age)
)
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Important steps for the import included the skip step to remove encoding
instructions put in by the creators of the dataset, as well as coding
the `.` values in the dataset to be `NA`. Other steps included using
`clean_names` to make variables snake case, as well as the assignment
requirements to properly encode character values for both the `sex` and
`apoe4` variables. Lastly, I went back and renamed `current_age` to
`bl_age` for easier personal understanding of the data.

- In total, 483 participants were recruited, with 479 remaining within
  the inclusion criteria for no MCI at baseline. Of these remaining, 93
  developed MCI.

- The average baseline age was 65.03 years old.

- 0.3 is the proportion of women in the study that were APOE4 carriers.
